# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docker-Explorer Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint coverage
        python setup.py install
    - name: Unit tests
      run: |
        pylint --rcfile=.pylintrc docker_explorer tests.py setup.py tools
        coverage run tests.py
    - name: Coverage
      run: |
        curl -o codecov.sh -s https://codecov.io/bash && /bin/bash ./codecov.sh
